[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "virtualpet"
description = "An example of a package developed with pyenv, built with build using setuptools, uploaded to PyPI using twine, and distributed via pip."
version = "0.1.0"
authors = [
  { name="Foo Barstein", email="foo.barstein@onepotcooking.com" },
  { name="Applejam-ovo", email="ql2138@nyu.edu" },
  { name="ElaineR02", email="pl2355nyu.edu" }
]
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["python", "package", "build", "tutorial"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/software-students-fall2024/3-python-package-straight-a"
"Repository" = "https://github.com/software-students-fall2024/3-python-package-straight-a.git"
"Bug Tracker" = "https://github.com/software-students-fall2024/3-python-package-straight-a/issues"

[project.scripts]
