[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "funtasks"
description = "A task management package that lets you add, complete, and fetch random tasks."
version = "0.1.1"
authors = [
  { name = "Jun Li", email= "jljune9li@gmail.com" },
  { name = "Natalie Ovcarov", email = "nataliovcharov@gmail.com"},
  { name = "Daniel Brito", email = "db4471@nyu.edu"},
  { name = "Alvaro Martinez", email = "amm9871@nyu.edu"}
]

license = { file = "LICENSE" }
readme = "README.md"
keywords = ["task management", "productivity", "random tasks"]
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/software-students-fall2024/3-python-package-java_and_the_scripts_"
"Repository" = "https://github.com/software-students-fall2024/3-python-package-java_and_the_scripts_.git"
"Bug Tracker" = "https://github.com/software-students-fall2024/3-python-package-java_and_the_scripts_/issues"

[project.scripts]
funtasks = "funtasks.__main__:main"
