[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Oracle"
description = "Built Oracle, a prophet that can do multiple things, including spit fortunes (fortune cookie), output a random decision (8ball), give a quick, random mood (vibe check), and output a random pet (petting zoo)."
version = "0.1.0"
authors = [
    {name: "Christopher Li", email:"cl6591@nyu.edu"}, 
    {name: "Julie Chen", email:"jc11048@nyu.edu"}, 
    {name: "Aneri Shah", email:"aneri.shah@nyu.edu"}, 
    {name: "Maddy Li", email:"maddyli@nyu.edu"}
]
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["oracle", "fortune", "8-ball", "vibe check", "petting zoo", "python package"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.scripts]
oracle = "oracle.cli:main"

[project.urls]
"Homepage" = "https://github.com/software-students-fall2024/3-python-package-burger-flippers"
"Repository" = "https://github.com/software-students-fall2024/3-python-package-burger-flippers.git"
"Bug Tracker" = "https://github.com/software-students-fall2024/3-python-package-burger-flippers/issues"


[project.optional-dependencies]
dev = ["pytest"]